"""
examples of individuals for the genetic algorithm
"""


# ----------#---------------------------------------------------#---------- #
# ---------- an skeleton of individual for the genetic algorithm ---------- #

class lambda_individual:
    def __init__(self, params=None, predefined_genome=None):

        # params is a tuple of a predefined size:
        parm1, param2 = params

        # the genome can be given by the genetic algorithm, or not
        self._genome = []  # private attribute, not used by the genetic algorithm
        if predefined_genome is None:
            # genome is not given, it can be generated by the individual
            pass
        else:
            # genome is given by the argument "predefined_genome", it must not be an other thing
            self.set_genome(predefined_genome)

        # the individual need to save his how fitness (a float or an integer)
        self.fitness = 0  # inited at 0, it will be calculated by the "evaluate" function

    # return all the gene of an individual in a 1D array, (call genome).
    # (used as DNA by the genetic algorithm)
    def get_genome(self):
        #
        return self._genome  # the function must return the genome in a 1D array

    # take the genome in argument and modify the internal genome of the individual with it.
    # (used for mutation and reproduction by genetic algorithm)
    def set_genome(self, genome):
        self._genome = genome

    # function restraint is use to restraint the individual
    def restraint(self):

        pass
        # return True if they are no restraint,
        # OR you can return False to kill the individual
        # OR you can return a number (it will be subtracted from the fitness)
        return True

    # this function is use to determine the "fitness" of an individual (higher is better)
    # (used to sort and to reproduce good individual)
    def evaluate(self):

        if self.restraint() is not bool:
            self.fitness -= self.restraint()  # if it is a number it subtracted the fitness
        return self.fitness  # the function must return the calculated fitness


# ----------#-----------------------------------------------------#---------- #
# ---------- a simple individual example for the genetic algorithm ---------- #

class simple_individual:
    def __init__(self, params=None, predefined_genome=None):

        import numpy as np

        # params is not used for this individual

        # the genome can be given by the genetic algorithm, or not
        self._genome = []  # private attribute, not used by the genetic algorithm
        if predefined_genome is None:
            # genome is not given, it can be generated by the individual
            self._genome = np.random.randint(-20, 20, 4)
        else:
            # genome is given by the argument "predefined_genome", it must not be an other thing
            self.set_genome(predefined_genome)

        # the individual need to save his how fitness (a float or an integer)
        self.fitness = 0  # inited at 0, it will be calculated by the "evaluate" function
        self.already_evaluate = False

    # return all the gene of an individual in a 1D array, (call genome).
    # (used as DNA by the genetic algorithm)
    def get_genome(self):
        #
        return self._genome  # the function must return the genome in a 1D array

    # take the genome in argument and modify the internal genome of the individual with it.
    # (used for mutation and reproduction by genetic algorithm)
    def set_genome(self, genome):
        self._genome = genome

    # function restraint is use to restraint the individual
    def restraint(self):

        summe = abs(self._genome[0]) + abs(self._genome[1]) + abs(self._genome[2]) + abs(self._genome[3])
        if summe > 40:
            return True

        # return False if it is not restraint,
        # OR you can return True to kill the individual
        # OR you can return a number (the absolute value will be subtracted from the fitness)
        return False

    # this function is use to determine the "fitness" of an individual
    # (used to sort and to reproduce good individual)
    def evaluate(self):

        terms = self._genome
        self.fitness = terms[0] * terms[1] + terms[2] - terms[3]

        if type(self.restraint()) is not bool:
            self.fitness += - abs(self.restraint())  # if it is a number it subtracted the fitness
        return self.fitness  # the function must return the calculated fitness
